### ISSUE TITLE
这个插件和LClender到底是啥关系啊？

### ISSUE THREAD

**Issue by shuanger051** [yudaren007007/qz-date#3]

**Comment by yudaren007007** [comment]
0.0两个项目没关系哈，我之前用的时候看`LClendar`太久没有维护更新了，bug太多，作者也没回应，就拿过来重构了一番，你反应的bug一会去修复。

**Comment by shuanger051** [comment]
nice，brother，你真给力啊。刚才我还以为我反馈的问题已经修复了呢，您赶紧的啊，哈哈。以前那个作者我也联系过，也没回，都一两年了哎。

**Comment by yudaren007007** [comment]
用iPhone测了微信自带浏览器和百度，没发现你说的问题呀，你用的什么？

**Comment by shuanger051** [comment]
当年开发的时候遇到的，在微信公众号嵌入的时候，也算是微信浏览器吧。一年前的事情了，现在都快忘记了。反正那个问题是一定存在的，我们现在也没改，不过这个是我们测试测出来的。先不管，哈哈，那个项目我们现在不维护了，在做新系统，等后面新系统出现这个问题的时候，我再骚扰你。3Q，Man.

**Comment by yudaren007007** [comment]
OKOK，欢迎骚扰
